openapi: 3.0.0
info:
  title: CSE341 Project 2 API
  description: API documentation for CSE341 Project 2 (Users & Cars CRUD)
  version: 1.0.0
servers:
  - url: https://cse341-project2-jys.onrender.com
    description: Production server
  - url: http://localhost:3000
    description: Local server
paths:
  /users:
    get:
      summary: Get all users
      tags: [Users]
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a new user
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/{id}:
    get:
      summary: Get user by ID
      tags: [Users]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
    put:
      summary: Update user by ID
      tags: [Users]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      security:
        - openIdConnect: []
      responses:
        '200':
          description: User updated
    delete:
      summary: Delete user by ID
      tags: [Users]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - openIdConnect: []
      responses:
        '200':
          description: User deleted
        '404':
          description: User not found
  /cars:
    get:
      summary: Get all cars
      tags: [Cars]
      responses:
        '200':
          description: List of cars
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Car'
    post:
      summary: Create a new car
      tags: [Cars]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
      responses:
        '201':
          description: Car created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
  /cars/{id}:
    get:
      summary: Get car by ID
      tags: [Cars]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Car found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
        '404':
          description: Car not found
    put:
      summary: Update car by ID
      tags: [Cars]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
      responses:
        '200':
          description: Car updated
    delete:
      summary: Delete car by ID
      tags: [Cars]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Car deleted
        '404':
          description: Car not found
  /login:
    get:
      summary: Redirect to OpenID Connect provider to start authentication
      tags: [Auth]
      description: |
        Initiates an OpenID Connect authentication flow using the express-openid-connect middleware.
        The server will redirect the user to the OIDC provider's authorization endpoint. After successful
        authentication the provider will redirect back to the application callback URL.
      responses:
        '302':
          description: Redirect to OpenID Connect provider
  /logout:
    get:
      summary: Logout the current user
      tags: [Auth]
      description: |
        Logs the user out of the application. When using express-openid-connect this will clear the local session
        and (optionally) redirect to the identity provider's logout endpoint depending on configuration.
      responses:
        '302':
          description: Redirect after logout

  /profile:
    get:
      summary: Get authenticated user's profile
      tags: [Auth]
      description: Returns the authenticated user's profile information obtained from the OpenID Connect provider. This endpoint is protected and requires a valid session.
      security:
        - openIdConnect: []
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '401':
          description: Not authenticated
components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string
        gender:
          type: string
        address:
          type: string
        phone:
          type: string
        employment:
          type: string
    Car:
      type: object
      properties:
        make:
          type: string
        model:
          type: string
        year:
          type: integer
        color:
          type: string
        vin:
          type: string
        mileage:
          type: integer
        bodyType:
          type: string
        fuel:
          type: string
        cc:
          type: integer
    Profile:
      type: object
      properties:
        sid:
          type: string
        nickname:
          type: string
        name:
          type: string
        picture:
          type: string
        updated_at:
          type: string
        email:
          type: string
        email_verified:
          type: string
        sub:
          type: string
  securitySchemes:
    Auth0:
      type: oauth2
      flows:
        password:
          authorizationUrl: https://dev-v5cfj1gszxaoe8zu.us.auth0.com/authorize
      
tags:
  - name: Users
    description: Operations related to users
  - name: Cars
    description: Operations related to cars
  - name: Auth
    description: Authentication and user profile operations
